[build]
  # Command to run to build your project, if applicable
  command = "npm install && npm run build"
  
  # Directory where the built files are located, if applicable
  publish = "build"

# Directory where Netlify Functions are located
[functions]
  directory = "PRODUCTAPI"

# Redirect all requests to your Express serverless function
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

# Define the function to handle server-side rendering
[[functions]]
  name = "index"
  path = "index.js"
